[theme]
base = "dark"  # Start with Streamlit’s dark theme
primaryColor = "#1f77b4"  # Blue for widgets (matches your plot’s historical line)
backgroundColor = "#0e1117"  # Dark background for main area
secondaryBackgroundColor = "#262730"  # Slightly lighter for sidebar
textColor = "#fafafa"  # Light text for readability
font = "sans serif"  # Keep default font